local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/sdhdbxub/sdhdbxub/main/Wh7Wa8Tb"))()
local window = library:new("Fragmented Darkness.lua X illusion")

local creds = window:Tab("看",'7734068321')

local bin = creds:section("Player information",true)

    bin:Label("You username:"..game.Players.LocalPlayer.Character.Name)
    bin:Label("You Exeutor:"..identifyexecutor())
    
    local bin = creds:section("关于的脚本和作者的信息",true)
    bin:Label("mshub暂不可用")
    bin:Label("沉默")
    bin:Label("模式脚本")
    bin:Label("版本Version:1 Beta")
    
local credits = creds:section("关闭",true)

credits:Toggle("脚本框架变小一点", "", false, function(state)
        if state then
        game:GetService("CoreGui")["frosty"].Main.Style = "DropShadow"
        else
            game:GetService("CoreGui")["frosty"].Main.Style = "Custom"
        end
    end)
    credits:Button("关闭脚本",function()
        game:GetService("CoreGui")["frosty"]:Destroy()
    end)

local creds = window:Tab("MODE",'7734068321')

local credits = creds:section("MODE",true)
    credits:Button("硬核模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/JevilOhio/Doors-Hardcore-noonie-ver-/main/Doors%20Hardcore%20(noonie)"))()
end)
    credits:Button("硬核重置",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/-v6/main/v6"))()
end)
    credits:Button("糟糕的硬核模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/bad-hardcore-/main/badharhcore"))()
end)
    credits:Button("无尽模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/symmetrical-octo-umbrella/main/ff"))()
end)
    credits:Button("碎片模式",function()
    loadstring(game:HttpGet("https://glot.io/snippets/gpw1ypnl5o/raw/main.lua"))()
end)
    credits:Button("生日模式",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/plamen6789/BirthdayModeDOORS/main/BirthdayModeScript'))()
end)
    credits:Button("困难模式",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/plamen6789/HardcoreScriptDOORS/main/HardcoreModeScript'))()
end)
    credits:Button("朦胧模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/HAZYMODE/HAZYMODE/HazyMode.lua"))()
end)
    credits:Button("恐惧模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/cool59572/freestuff/main/Mods/FearMode.lua"))()
end)
    credits:Button("单人恐惧",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/cool59572/freestuff/main/Fear_mode_multiplayer.lua"))()
end)
    credits:Button("巨魔模式",function()
    loadstring(game:HttpGet("https://glot.io/snippets/gotfeffesc/raw/main.lua"))()
end)
    credits:Button("极端模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/Moonsec-Extreme-mode/main/Extreme%20Mode.lua"))()
end)
    credits:Button("哈莫模式",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/anmoc/main/hamod"))()
end)
    credits:Button("噩梦模式",function()
    loadstring(game:HttpGet(("https://raw.githubusercontent.com/Drop56796/HARDCORE-FIXED-MODE-IN-GITHUB/HARDCORE-MODE-FIXED-IN-GITHUB/WORKLINKVERSITE%20THE%20HARDCORE%20MODE%20V2.5%20FIXED%20MAKE%20BY%20IN%20GITHUB.lua"),true))()
end)
    credits:Button("疯狂模式V5",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/thefigureblack/doors/main/insanemodev5.lua"))()
end)
    credits:Button("不可能模式",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Ukazix/impossible-mode/main/Protected_79.lua.txt'))()
end)
    credits:Button("Noah Dark Mode V1",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/Noah-Dark/Noah-Dark-Mode-Script-V1/Noah%20Dark.lua"))()
end)
    credits:Button("Insanity Fog Mode v1.4",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/Insanity-Fog-Mode-v1.4/Insanity-Fog-Mode-v1.4-Script/Insanity%20Fog%20Mode%20v1.4%20Script.lua"))()
end)

local creds = window:Tab("其他辅助之类",'7734068321')

local credits = creds:section("一些辅助",true)
    credits:Button("拆掉假门",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/ZcNPGJfQ"))()
end)
    credits:Button("删掉门的框架",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/4m2Nw1Kr"))()
end)
    credits:Button("走的很快",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/rqA4YPzi", true))()
end)
    credits:Button("走的贼慢",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/HFLkawSE", true))()
end)
    credits:Button("屏幕全亮",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/4LDKiJ5a"))()
end)
    credits:Button("给屏幕加点亮度",function()
    loadstring(game:HttpGet('https://pastebin.com/raw/CbRsLfts'))()
end)
credits:Button("类似于上帝模式但没上帝好",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/BaFjFuCk"))()
end)
credits:Button("没有火焰，seek预测…",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/kXanyBLY"))()
end)
credits:Button("最强汉化",function()
    loadstring(game:HttpGet("\104\116\116\112\115\58\47\47\112\97\115\116\101\98\105\110\46\99\111\109\47\114\97\119\47\54\53\84\119\84\56\106\97"))()
end)

local creds = window:Tab("复制QQ号:slience",'7734068321')

local credits = creds:section("QQ",true)
    credits:Button("slience",function()
    setclipboard("3756646428")
end)
