local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/sdhdbxub/sdhdbxub/main/Wh7Wa8Tb"))()
local window = library:new("Fragmented Dark.lua")

local creds = window:Tab("look Here!",'7734068321')

local bin = creds:section("Player information",true)

    bin:Label("You username:"..game.Players.LocalPlayer.Character.Name)
    bin:Label("You Exeutor:"..identifyexecutor())
    
    local bin = creds:section("国人制作 ★关于的脚本和作者的信息★",true)
    bin:Label("mshub is Script invalidation please Coming Soon")
    bin:Label("slience")
    bin:Label("Script Mode")
    bin:Label("Version:1 Beta")
    bin:Label("The linkvertise Script Make in Github")

    
local credits = creds:section("Close ui",true)

credits:Toggle("脚本框架变小一点", "", false, function(state)
        if state then
        game:GetService("CoreGui")["frosty"].Main.Style = "DropShadow"
        else
            game:GetService("CoreGui")["frosty"].Main.Style = "Custom"
        end
    end)
    credits:Button("Close ui",function()
        game:GetService("CoreGui")["frosty"]:Destroy()
    end)

local creds = window:Tab("MODE.lua",'7734068321')

local credits = creds:section("MODE",true)
    credits:Button("HardcoreMode.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/JevilOhio/Doors-Hardcore-noonie-ver-/main/Doors%20Hardcore%20(noonie)"))()
end)
    credits:Button("HardcoreRemakeMode.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/Hardcore-mode-Remake-V6/Hardcore-mode-Remake-V6/Hardcore%20mode%20Remake.lua"))()
end)
    credits:Button("bad HardcoreMode.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/bad-hardcore-/main/badharhcore"))()
end)
    credits:Button("EndlessMode.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/symmetrical-octo-umbrella/main/ff"))()
end)
    credits:Button("FragmentedMode.lua",function()
    loadstring(game:HttpGet("https://glot.io/snippets/gpw1ypnl5o/raw/main.lua"))()
end)
    credits:Button("birthdayMode.lua",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/plamen6789/BirthdayModeDOORS/main/BirthdayModeScript'))()
end)
    credits:Button("HellMode.lua",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/plamen6789/HardcoreScriptDOORS/main/HardcoreModeScript'))()
end)
    credits:Button("Hazymode.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/HAZYMODE/HAZYMODE/HazyMode.lua"))()
end)
    credits:Button("FearMode.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/cool59572/freestuff/main/Mods/FearMode.lua"))()
end)
    credits:Button("Fear multiplayer Mode.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/cool59572/freestuff/main/Fear_mode_multiplayer.lua"))()
end)
    credits:Button("Trollmode.lua",function()
    loadstring(game:HttpGet("https://glot.io/snippets/gotfeffesc/raw/main.lua"))()
end)
    credits:Button("ExtremeMode.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/Moonsec-Extreme-mode/main/Extreme%20Mode.lua"))()
end)
    credits:Button("HammerMode.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/munciseek/anmoc/main/hamod"))()
end)
    credits:Button("NightmareMode.lua",function()
    loadstring(game:HttpGet(("https://raw.githubusercontent.com/Drop56796/HARDCORE-FIXED-MODE-IN-GITHUB/HARDCORE-MODE-FIXED-IN-GITHUB/WORKLINKVERSITE%20THE%20HARDCORE%20MODE%20V2.5%20FIXED%20MAKE%20BY%20IN%20GITHUB.lua"),true))()
end)
    credits:Button("InsaneModeV5.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/thefigureblack/doors/main/insanemodev5.lua"))()
end)
    credits:Button("impossibleMode.lua",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Ukazix/impossible-mode/main/Protected_79.lua.txt'))()
end)
    credits:Button("Noah Dark Mode V1.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/Noah-Dark/Noah-Dark-Mode-Script-V1/Noah%20Dark.lua"))()
end)
    credits:Button("Insanity Fog Mode.lua",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Drop56796/Insanity-Fog-Mode-v1.4/Insanity-Fog-Mode-v1.4-Script/Insanity%20Fog%20Mode%20v1.4%20Script.lua"))()
end)

local creds = window:Tab("Other.txt",'7734068321')

local credits = creds:section("Other",true)
    credits:Button("拆掉假门",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/ZcNPGJfQ"))()
end)
    credits:Button("删掉门的框架",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/4m2Nw1Kr"))()
end)
    credits:Button("走的很快",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/rqA4YPzi", true))()
end)
    credits:Button("走的贼慢",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/HFLkawSE", true))()
end)
    credits:Button("屏幕全亮",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/4LDKiJ5a"))()
end)
    credits:Button("给屏幕加点亮度",function()
    loadstring(game:HttpGet('https://pastebin.com/raw/CbRsLfts'))()
end)
credits:Button("类似于上帝模式但没上帝好",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/BaFjFuCk"))()
end)
credits:Button("没有火焰，seek预测…",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/kXanyBLY"))()
end)
credits:Button("Bobhub In Moonsec V3.lua",function()
    loadstring(game:HttpGet("\104\116\116\112\115\58\47\47\112\97\115\116\101\98\105\110\46\99\111\109\47\114\97\119\47\54\53\84\119\84\56\106\97"))()
end)

local creds = window:Tab("复制QQ号:slience",'7734068321')

local credits = creds:section("QQ",true)
    credits:Button("slience",function()
    setclipboard("3756646428")
end)
